# apiVersion: cert-manager.io/v1alpha1
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "alongkot.sw@gmail.com"
    privateKeySecretRef:
      name: letsencrypt-prod
    # http01: {}
    solvers:
      - http01:
          ingress:
            class: nginx